### ISSUE TITLE
Static media in HTML (Jinja2) templates.

### ISSUE THREAD

**Issue by jpearsall** [SpaceWhale/aurora_informer#6]
This is particularly in regards to index/unsubscribe.html template files. Flask provides for static media in a way that doesn't make assumptions about your URL. [Here](http://flask.pocoo.org/docs/0.10/quickstart/#static-files) is the relevant part of the documents. I recall having an issue with implementation that, I believe, required some explicit defining of the static path. Feel free to let me know if you run into that and I'll poke around and see how to invoke it. This'll save you some painful/annoying grepping through your content later to update your paths to something more dynamic.

**Comment by SpaceWhale** [comment]
I have this partially implemented with a base.html which other pages extend. I'll plan in implementing this with the CSS shortly.

**Comment by SpaceWhale** [comment]
app structure has this implemented now.
